#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef RADARSDK_SWIFT_H
#define RADARSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#import <RadarSDK/RadarSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RadarSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface Radar (SWIFT_EXTENSION(RadarSDK))
/// Starts continuously ranging nearby beacons while the app is in the foreground, so
/// <code>trackVerified(beacons: true)</code> can attach nearby beacons without waiting on a new ranging
/// window.
/// Call this after <code>initialize</code> and after location permissions are granted, ideally when the
/// user enters a flow that calls <code>trackVerified(beacons: true)</code>, and call
/// <code>stopRangingBeacons()</code> when beacons are no longer needed. Ranging pauses automatically when
/// the app enters the background and resumes when it returns to the foreground. Requires
/// foreground location permissions and Bluetooth. Until ranging has run for 5 seconds,
/// <code>trackVerified(beacons: true)</code> ranges beacons as usual.
/// seealso:
/// https://radar.com/documentation/beacons
+ (void)startRangingBeacons;
/// Stops ranging beacons started with <code>startRangingBeacons()</code>.
/// seealso:
/// https://radar.com/documentation/beacons
+ (void)stopRangingBeacons;
@end

@class NSString;
/// Represents the chain of a place.
/// seealso:
/// https://radar.com/documentation/places
SWIFT_CLASS_NAMED("RadarChain")
@interface RadarChain : NSObject
/// The unique ID of the chain. For a full list of chains, see https://radar.com/documentation/places/chains.
/// seealso:
/// https://radar.com/documentation/places/chains
@property (nonatomic, readonly, copy) NSString * _Nonnull slug;
/// The name of the chain. For a full list of chains, see https://radar.com/documentation/places/chains.
/// seealso:
/// https://radar.com/documentation/places/chains
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The external ID of the chain.
@property (nonatomic, readonly, copy) NSString * _Nullable externalId;
/// The optional set of custom key-value pairs for the chain.
@property (nonatomic, readonly, copy) NSDictionary * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (NSArray<NSDictionary *> * _Nullable)arrayForChains:(NSArray<RadarChain *> * _Nullable)chains SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents the geometry of a geofence.
SWIFT_CLASS_NAMED("RadarGeofenceGeometry")
@interface RadarGeofenceGeometry : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RadarCoordinate;
/// Represents the geometry of a circle geofence.
SWIFT_CLASS_NAMED("RadarCircleGeometry")
@interface RadarCircleGeometry : RadarGeofenceGeometry
/// The center of the circle geofence.
@property (nonatomic, readonly, strong) RadarCoordinate * _Nonnull center;
/// The radius of the circle geofence in meters.
@property (nonatomic, readonly) double radius;
@end

/// Represents a location coordinate.
SWIFT_CLASS_NAMED("RadarCoordinate")
@interface RadarCoordinate : NSObject
/// The coordinate.
@property (nonatomic, readonly) CLLocationCoordinate2D coordinate;
- (nullable instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("RadarDelegateHolder")
@interface RadarDelegateHolder_Swift : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RadarEvent;
@class UNMutableNotificationContent;
SWIFT_CLASS("_TtC8RadarSDK23RadarEventNotifications")
@interface RadarEventNotifications : NSObject
/// Show local notifications for incoming events (geofence, beacon, trip).
/// Called by RadarDelegateHolder when events arrive.
+ (void)showNotificationsFor:(NSArray<RadarEvent *> * _Nonnull)events;
/// Builds notification content from campaign metadata. Returns nil if not a campaign
/// or missing required fields.
+ (UNMutableNotificationContent * _Nullable)extractCampaignContentFrom:(NSDictionary * _Nullable)metadata identifier:(NSString * _Nullable)identifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
enum RadarExpectedAddressConfidence : NSInteger;
/// Represents a comparison between the user’s location and the expected address set with <code>setExpectedAddress:</code>.
SWIFT_CLASS_NAMED("RadarExpectedAddress")
@interface RadarExpectedAddress : NSObject
/// The user’s expected address, as passed to <code>setExpectedAddress:</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull expectedAddress;
/// The formatted expected address, as geocoded by Radar. May be <code>nil</code> if the expected address could not be geocoded.
@property (nonatomic, readonly, copy) NSString * _Nullable formattedAddress;
/// The latitude of the geocoded expected address. May be <code>nil</code> if the expected address could not be geocoded.
@property (nonatomic, readonly, strong) NSNumber * _Nullable latitude;
/// The longitude of the geocoded expected address. May be <code>nil</code> if the expected address could not be geocoded.
@property (nonatomic, readonly, strong) NSNumber * _Nullable longitude;
/// A boolean indicating whether the user is at their expected address.
@property (nonatomic, readonly) BOOL atAddress;
/// The confidence of the match between the user’s location and their expected address. May be
/// <code>RadarExpectedAddressConfidenceUnknown</code> if confidence is not available.
@property (nonatomic, readonly) enum RadarExpectedAddressConfidence confidence;
/// The distance in meters between the user’s location and their expected address. May be <code>nil</code> if the expected
/// address could not be geocoded.
@property (nonatomic, readonly, strong) NSNumber * _Nullable distance;
/// Keeps <code>[[RadarExpectedAddress alloc] init]</code> from trapping on Swift’s unimplemented-initializer
/// stub, matching the zero-value <code>init</code> the other Objective-C model surfaces expose.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

/// The confidence levels for a match between the user’s location and their expected address.
typedef SWIFT_ENUM_NAMED(NSInteger, RadarExpectedAddressConfidence, "RadarExpectedAddressConfidence", open) {
  RadarExpectedAddressConfidenceUnknown = 0,
  RadarExpectedAddressConfidenceLow = 1,
  RadarExpectedAddressConfidenceMedium = 2,
  RadarExpectedAddressConfidenceHigh = 3,
};

/// Represents fraud detection signals for location verification.
/// warning:
/// Note that these values should not be trusted unless you called <code>trackVerified()</code> instead of
/// <code>trackOnce()</code>.
/// seealso:
/// https://radar.com/documentation/fraud
SWIFT_CLASS_NAMED("RadarFraud")
@interface RadarFraud : NSObject
/// A boolean indicating whether the user passed fraud detection checks. May be <code>false</code> if Fraud is not enabled.
@property (nonatomic, readonly) BOOL passed;
/// A boolean indicating whether fraud detection checks were bypassed for the user for testing. May be <code>false</code>
/// if Fraud is not enabled.
@property (nonatomic, readonly) BOOL bypassed;
/// A boolean indicating whether the request was made with SSL pinning configured successfully. May be <code>false</code>
/// if Fraud is not enabled.
@property (nonatomic, readonly) BOOL verified;
/// A boolean indicating whether the user’s IP address is a known proxy. May be <code>false</code> if Fraud is not enabled.
@property (nonatomic, readonly) BOOL proxy;
/// A boolean indicating whether the user’s location is being mocked, such as in the simulator or using a
/// location spoofing app. May be <code>false</code> if Fraud is not enabled.
@property (nonatomic, readonly) BOOL mocked;
/// A boolean indicating whether the user’s device or app has been compromised according to <code>DeviceCheck</code>. May
/// be <code>false</code> if Fraud is not enabled.
/// seealso:
/// https://developer.apple.com/documentation/devicecheck
@property (nonatomic, readonly) BOOL compromised;
/// A boolean indicating whether the user moved too far too fast. May be <code>false</code> if Fraud is not enabled.
@property (nonatomic, readonly) BOOL jumped;
/// A boolean indicating whether the user’s location is not accurate enough. May be <code>false</code> if Fraud is not
/// enabled.
@property (nonatomic, readonly) BOOL inaccurate;
/// A boolean indicating whether the user’s location is not accurate enough. May be <code>false</code> if Fraud is not
/// enabled.
@property (nonatomic, readonly) BOOL sharing;
/// A boolean indicating whether the user has been manually blocked. May be <code>false</code> if Fraud is not enabled.
@property (nonatomic, readonly) BOOL blocked;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;
@class RadarInAppMessage;
@class UIViewController;
SWIFT_CLASS_NAMED("RadarInAppMessageDelegate")
@interface RadarInAppMessageDelegate_Swift : NSObject <RadarInAppMessageProtocol>
+ (void)loadImage:(NSString * _Nonnull)url completionHandler:(void (^ _Nonnull)(UIImage * _Nullable))completionHandler;
/// Returns the view controller for the message to show, can be overwritten to display a custom view
- (void)createInAppMessageView:(RadarInAppMessage * _Nonnull)message onDismiss:(void (^ _Nonnull)(void))onDismiss onInAppMessageClicked:(void (^ _Nonnull)(void))onInAppMessageClicked completionHandler:(void (^ _Nonnull)(UIViewController * _Nonnull))completionHandler;
- (void)onInAppMessageButtonClicked:(RadarInAppMessage * _Nonnull)message;
- (void)onInAppMessageDismissed:(RadarInAppMessage * _Nonnull)message;
- (void)onNewInAppMessage:(RadarInAppMessage * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("RadarInAppMessage_Swift")
@interface RadarInAppMessage_Swift : RadarInAppMessage
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull metadata;
+ (RadarInAppMessage * _Nullable)fromDictionary:(NSDictionary<NSString *, id> * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<RadarInAppMessage *> * _Nonnull)fromArray:(id _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, id> * _Nonnull)toDictionary:(RadarInAppMessage * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("RadarInitializeOptions")
@interface RadarInitializeOptions : NSObject
@property (nonatomic) BOOL autoLogNotificationConversions;
@property (nonatomic) BOOL autoHandleNotificationDeepLinks;
@property (nonatomic) BOOL silentPush;
@property (nonatomic) BOOL trackVerifiedAutoFailover;
/// Request and resource timeout in seconds for standard API calls. Default 10 seconds.
/// Invalid values (non-finite or ≤ 0) fall back to the default; values are
/// clamped to the range 1…300.
@property (nonatomic) NSTimeInterval networkTimeoutInterval;
/// Minimum interval in seconds between deliveries of <code>RadarVerifiedDelegate.didChangeIP()</code>.
/// Default 10 seconds. Set to 0 to disable throttling (deliver every detected change).
/// Negative or non-finite values fall back to the default.
@property (nonatomic) NSTimeInterval ipChangeDebounceInterval;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDict:(NSDictionary * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

@class NSTimer;
@class CLLocationManager;
SWIFT_PROTOCOL("_TtP8RadarSDK29RadarLocationManagerSwiftHost_")
@protocol RadarLocationManagerSwiftHost
- (BOOL)started SWIFT_WARN_UNUSED_RESULT;
- (void)setStarted:(BOOL)started;
- (int32_t)startedInterval SWIFT_WARN_UNUSED_RESULT;
- (void)setStartedInterval:(int32_t)interval;
- (BOOL)sending SWIFT_WARN_UNUSED_RESULT;
- (NSTimer * _Nullable)timer SWIFT_WARN_UNUSED_RESULT;
- (void)setTimer:(NSTimer * _Nullable)timer;
- (void)cancelPendingShutdown;
- (void)requestLocation;
- (void)scheduleShutdownAfter:(NSTimeInterval)delay;
- (void)addCompletionHandler:(RadarLocationCompletionHandler _Nullable)completionHandler;
@property (nonatomic, readonly, strong) CLLocationManager * _Nonnull locationManager;
@end

@class UNNotification;
SWIFT_CLASS("_TtC8RadarSDK26RadarNotificationSwizzling")
@interface RadarNotificationSwizzling : NSObject
+ (void)swizzleNotificationCenterDelegate;
+ (void)swizzleApplicationDelegate;
+ (void)openURLFromNotification:(UNNotification * _Nonnull)notification;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNNotificationRequest;
SWIFT_CLASS("_TtC8RadarSDK22RadarNotificationUtils")
@interface RadarNotificationUtils : NSObject
+ (void)checkNotificationPermissionsWithCompletionHandler:(void (^ _Nullable)(BOOL))completionHandler;
/// Returns delivered notifications (registered minus still-pending).
/// Called from RadarAPIClient.m before each track request.
+ (void)getNotificationDiffWithCompletionHandler:(void (^ _Nonnull)(NSArray<NSDictionary<NSString *, id> *> * _Nonnull, NSArray * _Nonnull))completionHandler;
+ (void)updateClientSideCampaignsWithPrefix:(NSString * _Nonnull)prefix notificationRequests:(NSArray<UNNotificationRequest *> * _Nonnull)requests;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("RadarOperatingHours")
@interface RadarOperatingHours : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSArray<NSArray<NSString *> *> *> * _Null_unspecified hours;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the geometry of polygon geofence.
SWIFT_CLASS_NAMED("RadarPolygonGeometry")
@interface RadarPolygonGeometry : RadarGeofenceGeometry
/// The geometry of the polygon geofence. A closed ring of coordinates.
@property (nonatomic, readonly, copy) NSArray<RadarCoordinate *> * _Nullable _coordinates;
/// The calculated centroid of the polygon geofence.
@property (nonatomic, readonly, strong) RadarCoordinate * _Nonnull center;
/// The calculated radius of the polygon geofence in meters.
@property (nonatomic, readonly) double radius;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskIpGeometry")
@interface RadarRevealRiskIpGeometry : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull coordinates;
@end

/// Risk level for a Reveal Risk token, ordered from lowest to highest.
typedef SWIFT_ENUM_NAMED(NSInteger, RadarRevealRiskLevel, "RadarRevealRiskLevel", open) {
  RadarRevealRiskLevelNone = 0,
  RadarRevealRiskLevelLow = 1,
  RadarRevealRiskLevelMedium = 2,
  RadarRevealRiskLevelHigh = 3,
};

@class NSDate;
@class RadarRevealRiskTokenRisk;
@class RadarRevealRiskTokenNetwork;
@class RadarRevealRiskTokenDevice;
/// Represents device and network risk signals.
/// seealso:
/// https://radar.com/documentation/fraud
SWIFT_CLASS_NAMED("RadarRevealRiskToken")
@interface RadarRevealRiskToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull _id;
@property (nonatomic, readonly, copy) NSString * _Nullable token;
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresAt;
@property (nonatomic, readonly, strong) NSNumber * _Nullable expiresIn;
@property (nonatomic, readonly, strong) RadarRevealRiskTokenRisk * _Nonnull risk;
@property (nonatomic, readonly, strong) RadarRevealRiskTokenNetwork * _Nonnull network;
@property (nonatomic, readonly, strong) RadarRevealRiskTokenDevice * _Nonnull device;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskTokenDevice")
@interface RadarRevealRiskTokenDevice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceType;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceMake;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceModel;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceOSName;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceOSVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable xPlatformType;
@property (nonatomic, readonly, copy) NSString * _Nullable installId;
@property (nonatomic, readonly, copy) NSString * _Nullable appId;
@property (nonatomic, readonly, copy) NSString * _Nullable appName;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable appBuild;
@end

@class RadarRevealRiskTokenNetworkIpAddress;
@class RadarRevealRiskTokenNetworkPrivacy;
@class RadarRevealRiskTokenNetworkAsn;
SWIFT_CLASS_NAMED("RadarRevealRiskTokenNetwork")
@interface RadarRevealRiskTokenNetwork : NSObject
@property (nonatomic, readonly, strong) RadarRevealRiskTokenNetworkIpAddress * _Nullable ipAddress;
@property (nonatomic, readonly, strong) RadarRevealRiskTokenNetworkPrivacy * _Nullable privacy;
@property (nonatomic, readonly, strong) RadarRevealRiskTokenNetworkAsn * _Nullable asn;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskTokenNetworkAsn")
@interface RadarRevealRiskTokenNetworkAsn : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable asn;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSString * _Nullable domain;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable network;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskTokenNetworkIpAddress")
@interface RadarRevealRiskTokenNetworkIpAddress : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSString * _Nullable countryFlag;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable city;
@property (nonatomic, readonly, copy) NSString * _Nullable postalCode;
@property (nonatomic, readonly, strong) NSNumber * _Nullable latitude;
@property (nonatomic, readonly, strong) NSNumber * _Nullable longitude;
@property (nonatomic, readonly, copy) NSString * _Nullable connectionType;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nullable stateConfidence;
@property (nonatomic, readonly, copy) NSString * _Nullable countryConfidence;
@property (nonatomic, readonly, copy) NSString * _Nullable dma;
@property (nonatomic, readonly, copy) NSString * _Nullable dmaCode;
@property (nonatomic, readonly) BOOL stateAllowed;
@property (nonatomic, readonly) BOOL countryAllowed;
@property (nonatomic, readonly, copy) NSString * _Nullable layer;
@property (nonatomic, readonly, strong) RadarRevealRiskIpGeometry * _Nullable geometry;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskTokenNetworkPrivacy")
@interface RadarRevealRiskTokenNetworkPrivacy : NSObject
@property (nonatomic, readonly) BOOL hosting;
@property (nonatomic, readonly) BOOL proxy;
@property (nonatomic, readonly) BOOL relay;
@property (nonatomic, readonly, copy) NSString * _Nullable service;
@property (nonatomic, readonly) BOOL tor;
@property (nonatomic, readonly) BOOL vpn;
@property (nonatomic, readonly) BOOL residentialProxy;
@end

SWIFT_CLASS_NAMED("RadarRevealRiskTokenRisk")
@interface RadarRevealRiskTokenRisk : NSObject
@property (nonatomic, readonly) enum RadarRevealRiskLevel level;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull reasons;
@end

@class RadarRouteDistance;
@class RadarRouteDuration;
@class RadarRouteGeometry;
/// Represents a route between an origin and a destination.
/// seealso:
/// https://radar.com/documentation/api#routing
SWIFT_CLASS_NAMED("RadarRoute")
@interface RadarRoute : NSObject
/// The distance of the route.
@property (nonatomic, readonly, strong) RadarRouteDistance * _Nonnull distance;
/// The duration of the route.
@property (nonatomic, readonly, strong) RadarRouteDuration * _Nonnull duration;
/// The geometry of the route.
@property (nonatomic, readonly, strong) RadarRouteGeometry * _Nonnull geometry;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents the distance of a route.
SWIFT_CLASS_NAMED("RadarRouteDistance")
@interface RadarRouteDistance : NSObject
/// The distance in feet (for imperial units) or meters (for metric units).
@property (nonatomic, readonly) double value;
/// A display string for the distance.
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the duration of a route.
SWIFT_CLASS_NAMED("RadarRouteDuration")
@interface RadarRouteDuration : NSObject
/// The duration in minutes.
@property (nonatomic, readonly) double value;
/// A display string for the duration.
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the geometry of a route.
SWIFT_CLASS_NAMED("RadarRouteGeometry")
@interface RadarRouteGeometry : NSObject
/// The geometry of the route.
@property (nonatomic, readonly, copy) NSArray<RadarCoordinate *> * _Nullable coordinates;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents routes between multiple origins and destinations.
/// seealso:
/// https://radar.com/documentation/api#matrix
SWIFT_CLASS_NAMED("RadarRouteMatrix")
@interface RadarRouteMatrix : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Returns the route between the specified origin and destination.
/// \param originIndex The index of the origin.
///
/// \param destinationIndex The index of the destination.
///
///
/// returns:
/// The route between the specified origin and destination.
- (RadarRoute * _Nullable)routeBetweenOriginIndex:(NSInteger)originIndex destinationIndex:(NSInteger)destinationIndex SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSArray<NSDictionary *> *> * _Nonnull)arrayValue SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("RadarRouteModeUtils")
@interface RadarRouteModeUtils : NSObject
/// Returns a display string for a travel mode value.
/// \param mode A travel mode value.
///
///
/// returns:
/// A display string for the travel mode value.
+ (NSString * _Nonnull)stringForMode:(RadarRouteMode)mode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;
@class RadarTrackingOptions;
@class RadarUser;
@class RadarBeacon;
SWIFT_CLASS_NAMED("RadarSyncManager")
@interface RadarSyncManager : NSObject
+ (void)startWithInterval:(NSTimeInterval)interval;
+ (void)stop;
+ (void)fetchSyncRegion;
+ (BOOL)shouldTrackWithLocation:(CLLocation * _Nonnull)location options:(RadarTrackingOptions * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isNearSyncedRegionBoundaryWithLocation:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isOutsideSyncedRegionWithLocation:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isPoint:(CLLocation * _Nonnull)point insideCircleWithCenter:(CLLocationCoordinate2D)center radius:(double)radius SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasSyncedRegion SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasGeofenceStateChangedWithLocation:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasBeaconStateChangedWithRangedBeaconIds:(NSSet<NSString *> * _Nonnull)rangedBeaconIds SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasPlaceStateChangedWithLocation:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
+ (void)reconcileSyncStateWithUser:(RadarUser * _Nonnull)user;
+ (void)saveBeaconStateWithBeaconIds:(NSArray<NSString *> * _Nonnull)beaconIds;
+ (void)rollbackSyncState;
+ (void)markDwellFired:(NSString * _Nonnull)geofenceId;
+ (NSArray<RadarBeacon *> * _Nonnull)getObjCBeaconsFor:(CLLocation * _Nonnull)location SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents a time zone.
/// seealso:
/// https://radar.com/documentation/api#geocoding
SWIFT_CLASS_NAMED("RadarTimeZone")
@interface RadarTimeZone : NSObject
/// The ID of the time zone.
@property (nonatomic, readonly, copy) NSString * _Nonnull _id;
/// The name of of the time zone.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The time zone abbreviation.
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
/// The current time for the time zone.
@property (nonatomic, readonly, copy) NSDate * _Nonnull currentTime;
/// The UTC offset for the time zone.
@property (nonatomic, readonly) int32_t utcOffset;
/// The DST offset for the time zone.
@property (nonatomic, readonly) int32_t dstOffset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
@end

@class RadarTripOrder;
@class RadarTripLeg;
/// Represents a trip.
/// seealso:
/// https://radar.com/documentation/trip-tracking
SWIFT_CLASS_NAMED("RadarTrip")
@interface RadarTrip : NSObject
/// The Radar ID of the trip.
@property (nonatomic, readonly, copy) NSString * _Nonnull _id;
/// The external ID of the trip.
@property (nonatomic, readonly, copy) NSString * _Nullable externalId;
/// The optional set of custom key-value pairs for the trip.
@property (nonatomic, readonly, copy) NSDictionary * _Nullable metadata;
/// For trips with a destination, the tag of the destination geofence.
@property (nonatomic, readonly, copy) NSString * _Nullable destinationGeofenceTag;
/// For trips with a destination, the external ID of the destination geofence.
@property (nonatomic, readonly, copy) NSString * _Nullable destinationGeofenceExternalId;
/// For trips with a destination, the location of the destination geofence.
@property (nonatomic, readonly, strong) RadarCoordinate * _Nullable destinationLocation;
/// The travel mode for the trip.
@property (nonatomic, readonly) RadarRouteMode mode;
/// For trips with a destination, the distance to the destination geofence in meters based on the travel mode
/// for the trip.
@property (nonatomic, readonly) float etaDistance;
/// For trips with a destination, the ETA to the destination geofence in minutes based on the travel mode for
/// the trip.
@property (nonatomic, readonly) float etaDuration;
/// The status of the trip.
@property (nonatomic, readonly) RadarTripStatus status;
/// The optional array of trip orders associated with this trip.
@property (nonatomic, readonly, copy) NSArray<RadarTripOrder *> * _Nullable orders;
/// For multi-destination trips, the array of trip legs.
/// Each leg contains destination info, status, and metadata.
/// Use leg._id when calling updateTripLeg.
@property (nonatomic, readonly, copy) NSArray<RadarTripLeg *> * _Nullable legs;
/// For multi-destination trips, the ID of the current active leg.
@property (nonatomic, readonly, copy) NSString * _Nullable currentLegId;
- (nullable instancetype)initWithObject:(id _Nonnull)object;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a leg of a multi-destination trip.
/// seealso:
/// https://radar.com/documentation/trip-tracking
SWIFT_CLASS_NAMED("RadarTripLeg")
@interface RadarTripLeg : NSObject
/// The Radar ID of the leg. Set from server response.
/// Use this when calling updateTripLeg.
@property (nonatomic, readonly, copy) NSString * _Nullable _id;
/// The status of the leg. Set from server response.
@property (nonatomic, readonly) RadarTripLegStatus status;
/// The destination type for this leg.
/// When parsed from a server response, reflects the server’s <code>destination.type</code>.
/// Otherwise, inferred from which properties are set (geofence > address > coordinates).
@property (nonatomic, readonly) RadarTripLegDestinationType destinationType;
/// The date when the leg was created. Set from server response.
@property (nonatomic, readonly, copy) NSDate * _Nullable createdAt;
/// The date when the leg was last updated. Set from server response.
@property (nonatomic, readonly, copy) NSDate * _Nullable updatedAt;
/// The ETA duration in minutes to this leg’s destination. Set from server response.
@property (nonatomic, readonly) float etaDuration;
/// The ETA distance in meters to this leg’s destination. Set from server response.
@property (nonatomic, readonly) float etaDistance;
/// The tag of the destination geofence for this leg.
/// Use with destinationGeofenceExternalId for geofence-based destinations.
@property (nonatomic, copy) NSString * _Nullable destinationGeofenceTag;
/// The external ID of the destination geofence for this leg.
/// Use with destinationGeofenceTag for geofence-based destinations.
@property (nonatomic, copy) NSString * _Nullable destinationGeofenceExternalId;
/// The Radar ID of the destination geofence for this leg.
/// Alternative to using destinationGeofenceTag + destinationGeofenceExternalId.
@property (nonatomic, copy) NSString * _Nullable destinationGeofenceId;
/// The address string for the destination of this leg.
/// Use for address-based destinations.
@property (nonatomic, copy) NSString * _Nullable address;
/// The coordinates for the destination of this leg.
/// Use for coordinate-based destinations. Set latitude and longitude.
@property (nonatomic) CLLocationCoordinate2D coordinates;
/// Whether coordinates have been explicitly set.
@property (nonatomic, readonly) BOOL hasCoordinates;
/// The arrival radius in meters for coordinate-based destinations.
/// Only used when coordinates are set.
@property (nonatomic) NSInteger arrivalRadius;
/// The stop duration in minutes for this leg.
@property (nonatomic) NSInteger stopDuration;
/// An optional set of custom key-value pairs for this leg.
@property (nonatomic, copy) NSDictionary * _Nullable metadata;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Initializes a RadarTripLeg with the specified destination geofence tag and external ID.
/// \param destinationGeofenceTag The tag of the destination geofence.
///
/// \param destinationGeofenceExternalId The external ID of the destination geofence.
///
///
/// returns:
/// A new RadarTripLeg instance.
- (nonnull instancetype)initWithDestinationGeofenceTag:(NSString * _Nullable)destinationGeofenceTag destinationGeofenceExternalId:(NSString * _Nullable)destinationGeofenceExternalId;
/// Initializes a RadarTripLeg with the specified destination geofence ID.
/// \param destinationGeofenceId The Radar ID of the destination geofence.
///
///
/// returns:
/// A new RadarTripLeg instance.
- (nonnull instancetype)initWithDestinationGeofenceId:(NSString * _Nonnull)destinationGeofenceId;
/// Initializes a RadarTripLeg with the specified address.
/// \param address The address string for the destination.
///
///
/// returns:
/// A new RadarTripLeg instance.
- (nonnull instancetype)initWithAddress:(NSString * _Nonnull)address;
/// Initializes a RadarTripLeg with the specified coordinates.
/// \param coordinates The coordinates for the destination.
///
///
/// returns:
/// A new RadarTripLeg instance.
- (nonnull instancetype)initWithCoordinates:(CLLocationCoordinate2D)coordinates;
/// Returns the string representation of a trip leg status.
/// \param status The trip leg status.
///
///
/// returns:
/// The string representation.
+ (NSString * _Nonnull)stringForStatus:(RadarTripLegStatus)status SWIFT_WARN_UNUSED_RESULT;
/// Returns the trip leg status for a string representation.
/// \param string The string representation.
///
///
/// returns:
/// The trip leg status.
+ (RadarTripLegStatus)statusForString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
/// Returns the string representation of a trip leg destination type.
/// \param destinationType The trip leg destination type.
///
///
/// returns:
/// The string representation.
+ (NSString * _Nonnull)stringForDestinationType:(RadarTripLegDestinationType)destinationType SWIFT_WARN_UNUSED_RESULT;
/// Returns the trip leg destination type for a string representation.
/// \param string The string representation.
///
///
/// returns:
/// The trip leg destination type.
+ (RadarTripLegDestinationType)destinationTypeForString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
/// Creates a RadarTripLeg from a dictionary representation.
/// \param object The dictionary containing leg data.
///
///
/// returns:
/// A new RadarTripLeg instance, or nil if the dictionary is invalid.
+ (RadarTripLeg * _Nullable)legFromDictionary:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// Creates an array of RadarTripLeg objects from an array of dictionaries.
/// \param array The array of dictionaries containing leg data.
///
///
/// returns:
/// An array of RadarTripLeg instances, or nil if the array is invalid.
+ (NSArray<RadarTripLeg *> * _Nullable)legsFromArray:(NSArray * _Nullable)array SWIFT_WARN_UNUSED_RESULT;
/// Converts the leg to a dictionary representation for API serialization.
///
/// returns:
/// A dictionary representation of the leg.
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
/// Converts an array of legs to an array of dictionaries.
/// \param legs The array of RadarTripLeg instances.
///
///
/// returns:
/// An array of dictionary representations.
+ (NSArray<NSDictionary *> * _Nullable)arrayForLegs:(NSArray<RadarTripLeg *> * _Nullable)legs SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// An options class used to configure trip tracking.
/// seealso:
/// https://radar.com/documentation/sdk/ios
SWIFT_CLASS_NAMED("RadarTripOptions")
@interface RadarTripOptions : NSObject
/// A stable unique ID for the trip.
@property (nonatomic, copy) NSString * _Nonnull externalId;
/// An optional set of custom key-value pairs for the trip.
@property (nonatomic, copy) NSDictionary * _Nullable metadata;
/// For trips with a destination, the tag of the destination geofence.
@property (nonatomic, copy) NSString * _Nullable destinationGeofenceTag;
/// For trips with a destination, the external ID of the destination geofence.
@property (nonatomic, copy) NSString * _Nullable destinationGeofenceExternalId;
/// The scheduled arrival time for the trip.
@property (nonatomic, copy) NSDate * _Nullable scheduledArrivalAt;
/// For trips with a destination, the travel mode.
@property (nonatomic) RadarRouteMode mode;
@property (nonatomic) uint16_t approachingThreshold;
@property (nonatomic) BOOL startTracking;
/// For multi-destination trips, an optional array of trip legs.
@property (nonatomic, copy) NSArray<RadarTripLeg *> * _Nullable legs;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithExternalId:(NSString * _Nonnull)externalId destinationGeofenceTag:(NSString * _Nullable)destinationGeofenceTag destinationGeofenceExternalId:(NSString * _Nullable)destinationGeofenceExternalId;
- (nonnull instancetype)initWithExternalId:(NSString * _Nonnull)externalId destinationGeofenceTag:(NSString * _Nullable)destinationGeofenceTag destinationGeofenceExternalId:(NSString * _Nullable)destinationGeofenceExternalId scheduledArrivalAt:(NSDate * _Nullable)scheduledArrivalAt;
- (nonnull instancetype)initWithExternalId:(NSString * _Nonnull)externalId destinationGeofenceTag:(NSString * _Nullable)destinationGeofenceTag destinationGeofenceExternalId:(NSString * _Nullable)destinationGeofenceExternalId scheduledArrivalAt:(NSDate * _Nullable)scheduledArrivalAt startTracking:(BOOL)startTracking;
+ (RadarTripOptions * _Nullable)tripOptionsFromDictionary:(NSDictionary * _Nullable)dictionary SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents a trip order.
SWIFT_CLASS_NAMED("RadarTripOrder")
@interface RadarTripOrder : NSObject
/// The ID of the trip order.
@property (nonatomic, readonly, copy) NSString * _Nonnull _id;
/// The optional GUID of the trip order.
@property (nonatomic, readonly, copy) NSString * _Nullable guid;
/// The optional handoff mode of the trip order.
@property (nonatomic, readonly, copy) NSString * _Nullable handoffMode;
/// The status of the trip order.
@property (nonatomic, readonly) RadarTripOrderStatus status;
/// The optional date when the order was fired.
@property (nonatomic, readonly, copy) NSDate * _Nullable firedAt;
/// The optional number of fired attempts.
@property (nonatomic, readonly, strong) NSNumber * _Nullable firedAttempts;
/// The optional reason why the order was fired.
@property (nonatomic, readonly, copy) NSString * _Nullable firedReason;
/// The date when the order was last updated.
@property (nonatomic, readonly, copy) NSDate * _Nonnull updatedAt;
- (nullable instancetype)initWithId:(NSString * _Nonnull)id guid:(NSString * _Nullable)guid handoffMode:(NSString * _Nullable)handoffMode status:(RadarTripOrderStatus)status firedAt:(NSDate * _Nullable)firedAt firedAttempts:(NSNumber * _Nullable)firedAttempts firedReason:(NSString * _Nullable)firedReason updatedAt:(NSDate * _Nonnull)updatedAt OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithObject:(id _Nonnull)object;
+ (NSArray<RadarTripOrder *> * _Nullable)ordersFromObject:(id _Nonnull)object SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSDictionary *> * _Nullable)arrayForOrders:(NSArray<RadarTripOrder *> * _Nullable)orders SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)dictionaryValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
